name: Run PowerShell Command

on:
  push:
    branches:
      - dev  # Specify the branch to trigger the pipeline

jobs:
  run-powershell:
    runs-on: ubuntu-latest
    steps:

      - name: Get Commit Data
        id: commits_data
        run: echo "::set-output name=commits::'${{ toJson(github.event.commits) }}'"
        
      - name: Run PowerShell Command
        run: |
          Write-Host '${{ steps.commits_data.outputs.commits }}' | ConvertFrom-Json
        shell: pwsh
