name: Run PowerShell Command

on:
  push:
    branches:
      - dev  # Specify the branch to trigger the pipeline

jobs:
  run-powershell:
    runs-on: ubuntu-latest
    steps:

      - name: Run PowerShell Command
        run: |
          Write-Host $('${{ toJson(github.event.commits) }}' | ConvertFrom-Json) |  ForEach-Object { "● $(escape $_.message)" }
        shell: pwsh
