name: Run PowerShell Command

on:
  push:
    branches:
      - dev  # Specify the branch to trigger the pipeline

jobs:
  run-powershell:
    runs-on: ubuntu-latest
    steps:
      - name: Run PowerShell Command
        run: |
          $commits = ${{ github.event.commits }} | ConvertTo-Json
          Write-Host $commits
        shell: pwsh
